### ISSUE TITLE
Need help emcc run

### ISSUE THREAD

**Issue by nvcken** [timhutton/opengl-canvas-wasm#1]
WARNING:root:LLVM version appears incorrect (seeing "9.0", expected "6.0")

CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
===========================================================================
(no targets could be identified: [Errno 2] No such file or directory: '/usr/bin/llc')
===========================================================================
CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
ERROR:root:Cannot find /usr/bin/llvm-link, check the paths in ~/.emscripten

**Comment by timhutton** [comment]
I'm guessing you're on some sort of Linux. To diagnose the problem, could you run the following sequence of instructions and post the entire console output (if it doesn't work)?

```
mkdir test_emsdk
cd test_emsdk
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
cd ..
git clone https://github.com/timhutton/opengl-canvas-wasm.git
cd opengl-canvas-wasm
emcc main.cpp -std=c++11 -s WASM=1 -s USE_SDL=2 -O3 -o index.js
```

I've just tried this on Ubuntu (using WSL on Windows 10) and it works for me.

**Comment by nvcken** [comment]
It works, Thanks so much
BTW, I tried on OSX

**Comment by nvcken** [comment]
@timhutton one stupid question, would it works fine on mobile browser that without WASM support yet ?

**Comment by timhutton** [comment]
@nvcken I don't know. Most mobile browsers support WASM already. I think there's a way to fallback to javascript when WASM isn't available but I haven't tried it.
