### ISSUE TITLE
Why does it result error with no optimization option "-O0" ?

### ISSUE THREAD

**Issue by EJShim** [timhutton/opengl-canvas-wasm#2]
Hello
Thank you for your example using emscripten opengl with html

Everything works greatly except I try to give no optimization  "-O0"  option instead of "-O3" to compiler.

When "-O0" is set, it results error saying 

```
emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.
````

Do you have any Idea to resolve this?

Thanks

**Comment by timhutton** [comment]
I just tried with -O0 on Ubuntu (on WSL) and it worked fine, using: 
```
mkdir test_emsdk
cd test_emsdk
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
cd ..
git clone https://github.com/timhutton/opengl-canvas-wasm.git
cd opengl-canvas-wasm
emcc main.cpp -std=c++11 -s WASM=1 -s USE_SDL=2 -O0 -o index.js
```
Maybe double check that you haven't got any other changes? What operating system are you using?

**Comment by EJShim** [comment]
I tried using Windows and OSX operating system and both of them resulted same error on ```-O0``` option. The only thing I changed is the optimization option on emcc compiler. except usnig ```-O0```, everything works fine. Maybe there are some compatible issue or something according to the operating system. Thanks for your reply anyway.
