### ISSUE TITLE
Project is not working on WSL 2 Ubuntu

### ISSUE THREAD

**Issue by sempostma** [timhutton/opengl-canvas-wasm#5]
- Last version of emscripten
- Last version of Ubuntu for Windows (WSL 2)
- Fresh clone of the project (no changes)
![Schermafbeelding 2023-03-29 010854](https://user-images.githubusercontent.com/34186586/228387073-263f1560-3888-4a62-b7f4-c831bbf48110.jpg)
![Schermafbeelding 2023-03-29 011333](https://user-images.githubusercontent.com/34186586/228387449-256e185d-6c35-415d-863f-500d7cee5967.jpg)

Switching between white and black background works

**Comment by datacrystals** [comment]
I had the same issue but I was able to fix it by creating a vertex array right after initializing the context:

```cpp
    ...
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24); // after this line in their code

    GLuint vao;
    glGenVertexArraysOES(1, &vao);
    glBindVertexArrayOES(vao);

    ...
```

I think that there's some requirement to have a vertex array otherwise OpenGL complains. Hopefully that's helpful!

**Comment by sempostma** [comment]
That fixed it, thanks!
